### ISSUE TITLE
How to create a comment?

### ISSUE THREAD

**Issue by Quorafind** [Darakah/obsidian-comments-plugin#1]
Could you share a video about how to create comments on highlighted text?

**Comment by Darakah** [comment]
A comment is defined as follows:

<label class="ob-comment" title="..." style="..."> highlighted text <input type="checkbox"> <span> Comment </span>

<label class="ob-comment" title="This is the title to show in sidebar - it is hidden in the in-line page and it is optional!"> highlighted text - this text will be highlighted in preview mode and if clicked upon will cause a pop-up to show up containing the contents of the comment. <input type="checkbox"> <span> Comment pop-up  test that will appear when clicked! </span></label>

Three main sections:
- Info: title / style
- Highlighted text that will be shown in preview mode and allows to show the comment
- The actual pop-up comment

Up-dated the Read Me file with this, will post more detailed description soon 
Sorry for the delay
