### ISSUE TITLE
Can't close comments panels plural 

### ISSUE THREAD

**Issue by BadBunnie** [Darakah/obsidian-comments-plugin#13]
**What happened:**
I cannot close the comments panel(s) from the ribbon or shortcut key. 

**What I have tried:**
• disabling the plugin
• uninstalling the plugin
• Restarting obsidian
• Restarting the computer

**My workaround:**
Create a new vault.

Please see attached screenshots for further clarification.

![Obsidian_22B7X4t3Kp](https://user-images.githubusercontent.com/8090991/175291590-4d7aa137-1016-41bd-a252-68ca19a8b73e.png)
_Shows comments plugin is no longer  installed_

![Obsidian_o8nX9ymIhq](https://user-images.githubusercontent.com/8090991/175291599-ec42006d-08ec-4cc9-a4eb-b9a701c5ac69.png)
_Shows comments plugin is no longer  installed_

![Obsidian_ue4yV4tWkU](https://user-images.githubusercontent.com/8090991/175291605-296b5736-89ec-454c-90d5-7f1ae15772ff.png)
_Shows multiple command panels_

**Comment by a-rock-lobster** [comment]
Right click the button in the comments panel (symbol is the page with the folded corner).

**Comment by BadBunnie** [comment]
Thanks! When I reopened the vault today the plugin had completly uninstalled but I'll keep that in mind 😄
