### ISSUE TITLE
comments-plugin for pdf

### ISSUE THREAD

**Issue by JJger148** [Darakah/obsidian-comments-plugin#4]
Would it be possible to put a HTML layer on top of a PDF in Obsidian and then comment it with the comments plugin?

**Comment by Darakah** [comment]
Do you mean something like this? 

https://forum.obsidian.md/t/markdown-layer-on-top-of-pdf/12278/9

Can you clarify please.

**Comment by JJger148** [comment]
yes exactly

**Comment by Darakah** [comment]
Yea, I know this can be very useful. 
Given that the author in the thread I linked is currently working on it and the time needed to create this (which i am greatly lacking currently), I don't think it is wise to extend this plugin to cover that.

For now what I do currently is copy the section I wanna comment from the pdf into a note adding the comment there. 
Then adding a link to the specific pdf page (using obsidian's feature `#page=2` for e.g.), then highlight the same line in the pdf with the same color. (in the example image i have the cursor over the link showing a direct preview of the pdf page)

<img width="1383" alt="Screen Shot 2021-02-24 at 3 05 16 PM" src="https://user-images.githubusercontent.com/29651407/109012109-eba9e100-76b1-11eb-8e0c-7ff729e86d3e.png">
